### ISSUE TITLE
Task cannot be run on remote agent?

### ISSUE THREAD

**Issue by stefanegli** [wwwlicious/wwwlicious.bamboo.xunit#1]
Not sure what I am missing here, but I did not manage to run this task on a remote agent. I am getting this error:

> Could not execute task 'Check xUnit Results' no Plugin with key 'com.wwwlicious.xunit.xunit:xunitParser' is installed. 

Is this not supported or is something wrong with my setup?

**Comment by wwwlicious** [comment]
this looks like an issue with the plugin, thanks for raising this, will investigate further

**Comment by djaquez** [comment]
FYI, I am seeing the same thing when running on a remote agent.  Any work-arounds or expected fix date would be appreciated.  Thanks for making the plugin!

**Comment by Vertigo093i** [comment]
Dependency on `hamcrest`?
https://bitbucket.org/armotic/file-downloader/issues/3/version-130-doesnt-work-on-remote-agents
Although for me the plugin works on remote agents.

**Comment by wwwlicious** [comment]
Thanks for the reference @Vertigo093i . I didn't really get anywhere trying to resolve this before, will take another crack at it over the weekend. :+1:

**Comment by Vertigo093i** [comment]
Well, I doubt this time it is the hamcrest. Cause I also do not have it on my remote agents but the plugin installed without problems and even works (though incorrectly but this is subject to a separate issue which I'll create lately).

One should look into remote agent's logs and find the plugin installation entries. There might be an exception which should shed some light on the problem.

Otherwise it might be an issue with multiple agents running from the same base directory (as described in the Atlassian KB).

**Comment by blachniet** [comment]
Any update on this issue? Is it true that this plugin only works on local agents right now?

**Comment by wwwlicious** [comment]
It actually does work on remote agents and I see the error intermittently myself. Still not figured out what on earth is causing it I'm afraid. Not given up though!

**Comment by wwwlicious** [comment]
Updated to use native stax xml streaming apis, hopefully this resolves the issues from version 1.0.2 now available on the marketplace
