### ISSUE TITLE
Could not execute task 'Parse results' no Plugin with key 'com.wwwlicious.xunit.xunit:xunitParser' is installed.

### ISSUE THREAD

**Issue by Draftkings** [wwwlicious/wwwlicious.bamboo.xunit#3]
Hello, 

I installed 1.0.3 of the xUnit.Net Parser and it's currently failing when running in my Build Job.

Could not execute task 'Parse results' no Plugin with key 'com.wwwlicious.xunit.xunit:xunitParser' is installed.

**Comment by wwwlicious** [comment]
Can you post the build agent logs?

FYI: I've had this error occur before and reinstalling or restarting the agent resolved it so I would suggest trying that first.

**Comment by Vertigo093i** [comment]
I confirm that the plugin works at least on remote Windows agents.

1. What is your Bamboo's installation version?
2. Check that the problematic agent contains the plugin's .jar file in the plugins folder.
3. Dive into agent's logs especially at the moment of plugin installation. There could be an exception logged which prevented the plugin from being registered.
4. Check Atalssian's KB article about this error (Hercules should have provided you with a link).

See also https://github.com/wwwlicious/wwwlicious.bamboo.xunit/issues/1#issuecomment-320250351.

**Comment by Draftkings** [comment]
Thank you for the Feedback.

1. We are running Bamboo 5.14.1 
2. I see a plugin.7439933165588189545.xunit-1.0.3.jar in the %USERPROFILE%\bamboo-agent-home\pluging\user-installed directory
3. There are some Agent Log errors when trying to enable the Plugin
2017-10-30 12:39:12,646 ERROR [AgentRunnerThread] [OsgiPluginInstalledHelper] Cannot determine required plugins, cannot resolve bundle 'com.wwwlicious.xunit'
2017-10-30 12:39:14,337 ERROR [AgentRunnerThread] [OsgiPlugin] Detected an error (BundleException) enabling the plugin 'com.wwwlicious.xunit.xunit' : Unresolved constraint in bundle com.wwwlicious.xunit [36]: Unable to resolve 36.0: missing requirement [36.0] osgi.wiring.package; (osgi.wiring.package=com.atlassian.plugin.spring.scanner.annotation.component).  This error usually occurs when your plugin imports a package from another bundle with a specific version constraint and either the bundle providing that package doesn't meet those version constraints, or there is no bundle available that provides the specified package. For more details on how to fix this, see https://developer.atlassian.com/x/mQAN
2017-10-30 12:39:14,886 ERROR [AgentRunnerThread] [PluginEnabler] Unable to enable plugin com.wwwlicious.xunit.xunit
com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: com.wwwlicious.xunit.xunit
	at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:418)
4. I found this KB article https://confluence.atlassian.com/bamkb/tasks-do-not-run-on-agents-due-to-plugin-availability-errors-894139447.html but don't see any <bamboo-agent-home>/atlassian-bamboo-agent.log file

**Comment by wwwlicious** [comment]
@Draftkings thanks for the info. I'll take a look at the spring scanner dependencies :+1:

**Comment by donnib** [comment]
I have same problem on two agents which are MacOS but i don't think that makes a difference. I have no idea how to solve it.

**Comment by wwwlicious** [comment]
I have released version 1.0.4 updating the pom dependencies to try and resolve this error.

Since the error is coming from a transitive dependency and java isn't that familiar to me, I'm not really sure how to find the exact culprit but I can get it to load fine with a remote agent when debugging so I'm hoping it's finally fixed. 

The plugin has the following imports for the record
/plugins/servlet/system/console/bundles


Description | This is the xunit parser plugin for Atlassian Bamboo.
-- | --
Start Level | 1
Exported Packages | com.wwwlicious.xunit.impl,version=1.0.4
Imported Packages | com.atlassian.bamboo.build.logger,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.build.logger.interceptors,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.build.test,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.collections,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.configuration,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.results.tests,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.resultsummary.tests,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.task,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.utils.error,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.bamboo.v2.build,version=6.2.2 from org.apache.felix.framework (0)com.atlassian.plugin.osgi.factory,version=4.1.0 from org.apache.felix.framework (0)com.atlassian.sal.api.message,version=3.0.8 from org.apache.felix.framework (0)com.google.common.base,version=18.0.0 from org.apache.felix.framework (0)com.google.common.collect,version=18.0.0 from org.apache.felix.framework (0)javax.annotation,version=0.0.0.1_008_JavaSE from org.apache.felix.framework (0)javax.annotation,version=1.0.0 from org.apache.felix.framework (0)javax.xml.namespace,version=0.0.0.1_008_JavaSE from org.apache.felix.framework (0)javax.xml.namespace,version=0.0.0 from org.apache.felix.framework (0)javax.xml.stream,version=0.0.0.1_008_JavaSE from org.apache.felix.framework (0)javax.xml.stream,version=1.0.0 from org.apache.felix.framework (0)javax.xml.stream.events,version=0.0.0.1_008_JavaSE from org.apache.felix.framework (0)javax.xml.stream.events,version=1.0.0 from org.apache.felix.framework (0)net.jcip.annotations,version=1.0.0 from org.apache.felix.framework (0)org.apache.commons.io,version=2.4.0 from org.apache.felix.framework (0)org.apache.commons.lang,version=2.6.0 from org.apache.felix.framework (0)org.apache.commons.logging,version=1.1.1 from jcl.over.slf4j (6)org.eclipse.gemini.blueprint.context,version=2.0.0.BUILD-atlassian-m002 from org.eclipse.gemini.blueprint.core (3)org.eclipse.gemini.blueprint.service.exporter,version=2.0.0.BUILD-atlassian-m002 from org.eclipse.gemini.blueprint.core (3)org.eclipse.gemini.blueprint.service.exporter.support,version=2.0.0.BUILD-atlassian-m002 from org.eclipse.gemini.blueprint.core (3)org.eclipse.gemini.blueprint.service.importer.support,version=2.0.0.BUILD-atlassian-m002 from org.eclipse.gemini.blueprint.core (3)org.osgi.framework,version=1.7.0 from org.apache.felix.framework (0)org.osgi.framework,version=1.4.1 from org.apache.felix.framework (0)org.springframework.aop.support,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-aop (8)org.springframework.beans,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory.annotation,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory.config,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory.parsing,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory.support,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.beans.factory.xml,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-beans (9)org.springframework.context.annotation,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-context (10)org.springframework.core.io,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-core (12)org.springframework.osgi.context,version=4.1.0 from org.eclipse.gemini.blueprint.extender (4)org.springframework.stereotype,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-context (10)org.springframework.util,version=4.2.0.RELEASE from org.apache.servicemix.bundles.spring-core (12)!! org.w3c.dom,version=0.0.0.1_008_JavaSE from org.apache.felix.framework (0) -- Overwritten by Boot Delegation!! org.w3c.dom,version=0.0.0 from org.apache.felix.framework (0) -- Overwritten by Boot Delegation
Service ID 344 | Types: org.eclipse.gemini.blueprint.context.DelegatedExecutionOsgiBundleApplicationContext, org.eclipse.gemini.blueprint.context.ConfigurableOsgiBundleApplicationContext, org.springframework.context.ConfigurableApplicationContext, org.springframework.context.ApplicationContext, org.springframework.context.Lifecycle, java.io.Closeable, org.springframework.beans.factory.ListableBeanFactory, org.springframework.beans.factory.HierarchicalBeanFactory, org.springframework.context.MessageSource, org.springframework.context.ApplicationEventPublisher, org.springframework.core.io.support.ResourcePatternResolver, org.springframework.beans.factory.BeanFactory, org.springframework.core.io.ResourceLoader, java.lang.AutoCloseable, org.springframework.beans.factory.DisposableBean

**Comment by wwwlicious** [comment]
Hi @Draftkings. I'm closing this issue for now as I hope it is finally resolved in 1.0.4.

Please re-open if the error is still happening in that version or higher.
