### ISSUE TITLE
Will this parse trx files and how to test parse?

### ISSUE THREAD

**Issue by dasjestyr** [wwwlicious/wwwlicious.bamboo.xunit#4]
So `dotnet test` and `dotnet xunit` provide different options and currently `dotnet xunit` simply doesn't work for me. We can no long specify `dotnet test -xml` but we can specify `dotnet test --logger trx`. Will this plug-in parse that?

Also, is there any way to test run a file through the parser without having to run the build plan?

**Comment by wwwlicious** [comment]
@dasjestyr Thanks for contributing 👍 

So a few things in there so I'll try and cover each of them.

So firstly, the plugin will not currently parse .trx files. I'm not familiar with the format so I don't know if there would be any issues with getting the information bamboo requires for logging test results.

Unfortunately MS kinda burned the existing ecosystem with the dotnet cli. `dotnet xunit` is prime example of this. In order to use the dotnet cli extensibility model, you add them against projects rather than solutions. This is why `dotnet xunit` won't run against a solution at present, only per project.

AFAIK there is no way to use a dotnet cli tool against a solution which is why you end up falling back to the `dotnet test` OOTB using MS test discovery. I haven't researched this much though but I found [similar issues with other projects](https://github.com/fsprojects/Paket/issues/2497)

Iterating through projects to run `dotnet xunit` will also error if the project is not a test project (so requires some means of detection or if dotnet restore is not run against the individual project (dotnet restore against the solution will not work for the cli tools I think) 
If this was done however, the plugin could pick up and parse mulitple xunit result files using the wildcard path globs that you can specifiy.

Another possibility would be if loggers could be customised to restore xunit xml format output but I say that again without having researched the topic.

Finally, you can't run a file through the parser without running a build plan...but you can parse files not generated by it (under the advanced options is a checkbox for this). By not cleaning a build directory and skipping/disabling any build tasks other than the parsing, you can parse xunit results which is what I do for testing usually.

That said, bamboo's test reporting api isn't the nicest compared with other CI servers and xunit itself has a lack of support for bamboo test output.  When running on CI servers like TeamCity for example, xunit console runner will detect this and output the results to the logs and TC has nice support for streaming log interception to collect these results.....whereas Bamboo's log interception again leaves a lot to be desired. 

[EDIT] 
so it looks like there is already a logger for xunit - https://github.com/Faizan2304/LoggerExtensions
if you install this package in your test projects, you should be able to specify the path to generate an xunit v2 format file
